### ISSUE TITLE
Php 7 not compatibel

### ISSUE THREAD

**Issue by Harrij2Watch** [moewe-io/favpress.com#38]
##

Hi my website uses Favpress 2017.10.85 but running php 7 it seems not compatible .   Is this a known limitation ?

# Source

**Title:** Support
**URL:** /support.html

**Comment by scrobbleme** [comment]
Hello @Harrij2Watch,

Generally it should be compatible, at least I don't know any issue regarding PHP 7.

What exactly is not working? Do you have some error log?

**Comment by Harrij2Watch** [comment]
Hi, Thanks for your response. This is what I get


--------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
--------------------------------------------------------------------------------------------------------------------------------
 544 | ERROR | preg_replace() - /e modifier is deprecated since PHP 5.5 and removed since PHP 7.0
————————————————————————————————————————————————————————————————

**Comment by scrobbleme** [comment]
@Harrij2Watch Thank you, I've probably found the line and will look into it.

**Comment by scrobbleme** [comment]
This should be fixed now.
